baseurl: "https://lawS21.classes.ryansafner.com/"
languageCode: "en-us"
title: "Economics of the Law"
theme: "rvs-tufte-hugo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Assignments
      url: /assignments/
      weight: 3
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Resources
      url: /resources/
      weight: 5
    - name: Slack
      url: "https://hoodcollegeeconomics.slack.com"
      weight: 7
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Ryan Safner
  thumbnail: /images/law_hex.png
  instructor: 
    name: Dr. Ryan Safner
    email: safner@hood.edu
    url: "https://www.ryansafner.com"
    twitter: ryansafner
    github: ryansafner
    office: 118 Rosenstock
  course:
    number: ECON 315
    semester: Spring 2021
    days: "TuTh"
    time: "11:30 AM–12:45 PM"
    location: 'Meets on Zoom'
    twitter: ryansafner
    dates: "February 1–May 21, 2021"
    github: "ryansafner/microS21"
    slack: "http://hoodcollegeeconomics.slack.com"
    copyrightYear: "2020-2021"
    contactDetails: >-
      Office hours: Tu/Th 3:30—5:00 PM
  university: 
    name: Hood College
    url: "https://www.hood.edu"
  school:
    name: George B. Delaplaine, Jr. School of Business
    url: "https://www.hood.edu/academics/departments/george-b-delaplaine-jr-school-business"
  description: "Economics of the Law"
  primaryColor: "#b14848" #5E81AC
  secondaryColor: "#4282c6" #D08770
  credits: >- 
    [Credits](/credits)
  logo:
    url: /images/law_hex.png
    alt: Law
  meta:
    twitterSite: "@ryansafner"
    twitterCreator: "@ryansafner"
    fbAuthor: "https://www.facebook.com/ryansafner"

markup:
  goldmark:
    renderer:
      unsafe: true
